# Generated by Django 4.1 on 2022-08-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=150)),
                ('sender_email', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=150)),
                ('text_body', models.TextField()),
            ],
        ),
    ]
