# Generated by Django 4.1 on 2022-08-18 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_projects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
