# Generated by Django 4.1 on 2022-08-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_projects_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='images',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
